# Generated by Django 5.0.6 on 2024-05-17 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fotograrfia',
            new_name='Fotografia',
        ),
    ]
