# Generated by Django 5.0.6 on 2024-05-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_rename_fotograrfia_fotografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('ESTRELA', 'Estrela'), ('GALÁXIA', 'Gláxia'), ('PLANETA', 'Planeta')], default='', max_length=100),
        ),
    ]
